### ISSUE TITLE
Clearing out phone input

### ISSUE THREAD

**Issue by jayrbolton** [yutakahoulette/snabbdom-form-helpers#2]
Line 81 in index is causing some trouble for me:
```
...
 , props: props(obj.name, obj.placeholder, obj.value && Number(obj.value) ? formatPhone(obj.value) : '')
...
```

We probably don't want to blank out the form field if it the phone number is a string, especially since phone numbers are probably saved with spaces, hyphens, and parens

**Comment by yutakahoulette-zz** [comment]
will take a look
